apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-play-example
  labels:
    app: kubernetes-play-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-play-example
  template:
    metadata:
      labels:
        app: kubernetes-play-example
    spec:
      containers:
      - name: kubernetes-play-example
        image: mrbbarton/kubernetes-play-example:1.1-SNAPSHOT
        ports:
        - containerPort: 9000
        envFrom:
        - secretRef:
            name: kubernetes-play-example

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-play-example-service
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-play-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000